### ISSUE TITLE
what problem was solved by latest commit (abb1d147211d6daf82f484d603990135ac80f393)?

### ISSUE THREAD

**Issue by whanrott** [gbateson/moodle-qtype_ordering#15]
I'm using the Longest Ordered Subset marking for with your Ordering plugin. I see that you've committed changes to this marking type. The marking before your commit looked ok to me in testing. Please explain what was wrong with it.

Thank you for contributing this useful plug-in.

**Comment by gbateson** [comment]
Thank for using the Ordering question type. I'm glad to hearing it is proving to be a useful plugin for you.

Before the recent commit, in the sequence 1-3-2-4-5-6, the subset 1-2 was selected as the "correct" part of the response. This is not the expected behavior. After the commit, the subset 3-4-5-6 is selected as the correct response.

I recommend you arrange for the Ordering question type on your Moodle site to updated at the next convenient opportunity.

regards,
Gordon

**Comment by gbateson** [comment]
I will close this issue now. Please feel free to re-open if you wish to continue this conversation.
