### ISSUE TITLE
Missing answer/response summary in response exports & preview

### ISSUE THREAD

**Issue by inks007** [gbateson/moodle-qtype_ordering#22]
Hi Gordon,

I am unable to view response summary for the Ordering question type whilst in Quiz -> Results -> Responses.
![image](https://user-images.githubusercontent.com/12200916/27745286-6298871e-5df5-11e7-9946-353c5650a4e7.png)

Attempting to "download table data as" csv, xlsx, html or json also fails, showing nothing or "" for the Ordering question response. Below is the JSON output.

`[["inks007","inks007","","","","my@email.com","Finished","1 July 2017  12:33 AM","1 July 2017  12:33 AM","8 secs","6.00","","True"]]`

The responses render correctly whilst in the "Review attempt" page.
 
I am also unable to view the "right answer summary" and "response summary" whilst in question preview mode.
![image](https://user-images.githubusercontent.com/12200916/27745033-6d75f97e-5df4-11e7-8653-224aedf34f4b.png)

I am on Moodle 3.3+ (Build: 20170622) and using qtype_ordering version 2017-04-26 (58).
Help/fix would be appreciated. And thank you for making this question type available.

**Comment by gbateson** [comment]
Thank for alerting me to this issue.

I have modified the "summarize_response()" method (in question.php) so that it will return a summary of the current or correct response for use in the "Technical Information" area or the "Response report". Note that HTML tags, such as images, will be removed, and any remaining text will be truncated to 10 characters.

Please arrange for the Ordering question type to be updated at the next convenient opportunity.

Best regards,
Gordon

**Comment by inks007** [comment]
Thank you. Works perfectly for all new responses.
