### ISSUE TITLE
Number/letter no longer tracks with dragged item

### ISSUE THREAD

**Issue by HuongNV13** [gbateson/moodle-qtype_ordering#51]
Hi @gbateson,

I found an issue as below:

![image](https://user-images.githubusercontent.com/11548406/70044957-def52500-15f5-11ea-9bd0-351ccd23f7a0.png)

This work normally before.
We need to keep the number/letter when dragging the item.

Fixed will be provided soon.

**Comment by timhunt** [comment]
Just commenting that I am pretty sure this used to work when we first implemented the answer numbering feature, although I cannot immediately see which change, if any, broke it.

We would be most grateful if you could review this Gordon, because we would like to deploy this fix, and we normally like to wait until bug-fixes have been integrated upstream before we deploy them to our live servers.

Also, Huong, there was one bit of the patch that was not completely obvious to me (the width: 100%). I am sure it is there for a reason, but I could not work out what. Explaining might help with the review.

Thanks.

**Comment by HuongNV13** [comment]
Thanks Tim for your comment.

I have made some comments to explain at https://github.com/gbateson/moodle-qtype_ordering/pull/52#discussion_r355914263

Thanks,
