### ISSUE TITLE
Ordering: better define 'rows' for items in horizontal list

### ISSUE THREAD

**Issue by SangNguyenAnh** [gbateson/moodle-qtype_ordering#55]
Depends on order of responses in horizontal list, I assume it's because each image for each 'answer' is slightly different in height.
![issue](https://user-images.githubusercontent.com/68416287/96403171-d6074500-1201-11eb-9656-c744a1394b89.PNG)

This would not, of course, be a problem if all images were precisely the same height, but as a general point, could we do anything where each 'row' is defined by the tallest image item, and thus any items on the additional rows would be left-aligned.
![expect](https://user-images.githubusercontent.com/68416287/96403271-18c91d00-1202-11eb-993a-dd19352e878d.PNG)

**Comment by gbateson** [comment]
Hi SangNguyenAnh,
as you have noticed using images of varying sizes results in an uneven layout.

We expect the items to be in neat horizontal rows, but they are not.
One or more of the middle rows contains fewer than other rows.
This happens because the items are positioned using CSS "float" parameter.

We could remedy this if the items were positioned using CSS "flex" layout.
However, until that is done, the workaround is to make the images the same size.
Do you know how to do that?

**Comment by SangNguyenAnh** [comment]
The "rows" what I mean they are aligned left and the tallest item's height ends in above.
This would not, of course, be a problem if all images were precisely the same height, but user can insert many things into question, like a music, this is a potential slight layout issue.
Of course, we can use CSS "flex" layout. I have a commit to improve it, and I'll create new pull request soon.

**Comment by gbateson** [comment]
Thank you. Please consider also, situations where (1) items vary in width, and (2) items vary in height and width.

**Comment by gbateson** [comment]
Thank you so much Sang. I have merged these changes into the master branch as part of Tim's pull request #72.
